pipeline {
    agent any
    environment {
        LC_ALL = 'en_US.UTF-8'
        LANG = 'en_US.UTF-8'
    }
    stages {
        stage('Checkout') {
            steps {
                // 소스코드 체크아웃
                checkout scm
            }
        }
        stage('Build') {
            steps {
                // Java 파일들을 컴파일하여 생성된 클래스 파일을 classes 디렉토리에 저장
                sh 'javac -encoding UTF-8 -d classes -cp mission2/src/**/*.java'
            }
        }
        stage('Test') {
            steps {
                // JUnit 5 테스트 실행을 위한 classpath 설정
                script {
                    def classpath = "classes:mission2/lib/junit-platform-console-standalone-1.7.1.jar"
                    // JUnit 5 테스트 실행
                    sh "java -Dfile.encoding=UTF-8 -cp ${classpath} org.junit.platform.console.ConsoleLauncher --scan-classpath > test_results.txt"
                }
            }
        }
        stage('Performance Test') {
            steps {
                // PerformanceTest 실행
                script {
                    def classpath = "classes"
                    // PerformanceTest 클래스 실행
                    sh "java -Dfile.encoding=UTF-8 -cp ${classpath} performanceTest.PerformanceTest > performance_test.txt"
                }
            }
        }
    }
    post {
        always {
            // 테스트 결과 파일을 저장하기 위해 아카이브
            archiveArtifacts artifacts: 'test_results.txt, performance_test.txt'
        }
        failure {
            echo 'Build or test failed'
        }
        success {
            echo 'Build and test succeeded'
        }
    }
}
